config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  get '/users/sign_out' => 'devise/sessions#destroy'

  get 'my_flats', to: 'flats#my_flats'

  resources :flats do
    resources :bookings, only: %i[new create]

    collection do
      get :search
    end

    member do
      get :reviews
    end

    resources :bookings, only: [ :new, :create ]
  end

  resources :bookings, except: [ :new, :index, :create ] do
    resources :reviews, only: [ :new, :create ]
  end

  resources :reviews, except: [ :new, :create ]

  get '/bookings', to: 'bookings#index'

  get '/error', to: 'errors#not_found'

  get "*path", to: redirect("/error")
end

app/models/flat.rb
class Flat < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user

  has_many :bookings

  has_one_attached :photo
  has_many :reviews, through: :bookings


  validates :price_per_day, presence: true
  validates :address, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :capacity, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_country_city_address,
    against: [ :country, :city, :address ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  def average_rating
    if self.bookings.empty?
      return {
        average: 0,
        num: 0
      }
    else
      ratings = []
      number = 0
      self.bookings.each do |booking|
        if booking.review
          number += 1
          ratings << booking.review.rating
        else
          next
        end
      end
      if ratings.empty?
        return {
          average: 0,
          num: 0
        }
      else
        return {
          average: ((ratings.sum) / ratings.count),
          num: number
        }
      end
    end
  end

  def reviews
    reviews = []
    unless self.bookings.empty?
      self.bookings.each do |booking|
        reviews << booking.review if booking.review
      end
    end
    return reviews
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_user, :database_search
  before_action :find_flat, only: %i[show edit update destroy reviews]

  def index
    # @flats = Flat.all
    @flats = policy_scope(Flat)

      @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window: render_to_string(partial: "info_window", locals: { flat: flat }),
        #image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
      }
    end
  end

  def new
    @flat = Flat.new
    authorize @flat
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user_id = @user.id
    authorize @flat
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def show
    @flat = Flat.find(params[:id])
    @booking = Booking.new
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to my_flats_path
  end

  def my_flats
    @flats = current_user.flats
    authorize @flats
  end

  def search
    if params[:query].present?
      @flats = Flat.search_by_country_city_address(params[:query])
    else
      @flats = Flat.all
    end
    @count = @flats.count
    @query = params[:query]

    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window: render_to_string(partial: "info_window", locals: { flat: flat }),
        #image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
      }
    end
    authorize @flats
    # authorize @markers
  end

  def reviews
    unless @flat.reviews.empty?
      @reviews = @flat.reviews
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:price_per_day, :city, :country, :address, :photo, :start_date, :end_date, :description, :capacity)
  end

  def find_flat
    if Flat.find_by(id: params[:id]).nil?
      redirect_to error_path
    else
      @flat = Flat.find(params[:id])
      authorize @flat
    end
  end

  def find_user
    @user = current_user
  end

  def database_search
    @markers = Flat.all
  end
end

app/views/flats/_info_window.html.erb
<%= link_to flat do %>
  <% if flat.photo.key.nil? %>
    <%= image_tag "no-image.png", class:"img-fluid width: 100% height: auto" %>
  <% else %>
    <%= cl_image_tag flat.photo.key, crop: :fill, class:"img-fluid width: 100% height: auto" %>
  <% end %>
  <div class="map-card">
    <p><span class="font-weight-bold" style="font: size 15px;"><i class="fa fa-location-arrow"></i></span>  <%= flat.address %> <strong><%= flat.city %></strong></p>
    <p><span class="font-weight-bold" style="font-size:15px;"><i class="fa fa-user"></i></span>  <%= flat.capacity %> people</p>
    <p>€/day <span class="font-weight-bold" style="font-size:30px; text-align:right; font-family:"><%= flat.price_per_day %></span></p>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Rental details</h1>
<div class="container">
  <div class="rental_form">
    <%= simple_form_for [ @flat ] do |f| %>
      <%= f.input :description %>
      <%= f.input :price_per_day %>
      <%= f.input :country, :as => :string %>
      <%= f.input :city %>
      <%= f.input :address %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <%= f.input :capacity %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Edit flat", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/flats/index.html.erb
<h1 class="text-center">All Available Flats</h1>
<div class="px-5 flats-map-grid">
  <div id="map"
    style="width: 100%;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <div class="flat-cards">
    <% @flats.each do |flat| %>
      <div class="card mb-2">
        <div class="card-block p-3">
          <div class="flats-photo">
            <% if flat.photo.key.present? %>
              <%= cl_image_tag flat.photo.key, class:"card-img-top index-image" %>
            <% else %>
            <%= image_tag("unknown.jpg", class:"card-img-top my_flat_image index-image") %>
            <% end %>
          </div>
          <strong><p class="card-title"><%= flat.address %></p></strong>
          <p class="card-subtitle text-muted"><span class="font-weight-bold">Price Per Day:</span> <%= flat.price_per_day %> Euros</p>
          <small class="card-text p-y-1"><span class="font-weight-bold">Capacity:</span> <%= flat.capacity %> people</small><br>
          <%= link_to 'Check it out!', flat, class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/my_flats.html.erb
<h1>My flats</h1>

<div class="my_flats_page">
  <div class="my_flats_container">

    <% unless current_user.flats.nil? %>
      <% @flats.each do |flat| %>
        <div class="flat_row">
          <div class="photo">
            <% if flat.photo.key.present? %>
              <%= cl_image_tag(flat.photo.key, class:"my-flat-image") %>
            <% else %>
              <%= image_tag("unknown.jpg", class:"my-flat-image") %>
            <% end %>
            <p><%= flat.address %></p>
          </div>

          <div class="d-flex align-items-center">
            <% if policy(flat).edit? %>
              <%= link_to 'Edit', edit_flat_path(flat), class:"btn btn-primary" %>
            <% end %>
                      <% unless flat.bookings.any? %>
          <div class="remove_flat_button">

            <%= link_to flat_path(flat), method:"delete", data: { confirm: "Are you sure?" }, class:"bin" do %>
            <i class="fa fa-trash" aria-hidden="true"></i>

            <% end %>
          </div>
          </div>


          <% else %>
          <div class="remove_flat_button_disabled">
            <i class="fa fa-trash" aria-hidden="true" title="This flat has ongoing booking"></i>
          </div>
          <% end %>
          </div>
        </div>



        </div>
        <hr>
      <% end %>
    <% end %>
    <div class="d-flex align-items-center">
    <%= link_to "Add a new flat", new_flat_path(@flat), class:"btn btn-primary add_new_flat" %>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<h1>Rental details</h1>
<div class="container">
  <div class="rental_form">
    <%= simple_form_for [ @flat ] do |f| %>
      <%= f.input :description %>
      <%= f.input :price_per_day %>
      <%= f.input :country, :as => :string %>
      <%= f.input :city %>
      <%= f.input :address %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <%= f.input :capacity %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Add flat", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/flats/reviews.html.erb
<h1><span class="text-muted"><%= @flat.address %></span> Reviews (<%= @flat.reviews.count %> opinions)</h1>
<div class="container">
  <div class="row d-flex justify-content-center">
    <% @flat.reviews.each do |review| %>
      <div class="review-card col-4 shadow-sm m-2 border">
        <div>
          <% if @flat.photo.key.nil? %>
            <%= image_tag "no-image.png", class:"img-fluid width: 100% height: auto" %>
          <% else %>
            <%= cl_image_tag @flat.photo.key, class:"img-fluid width: 100% height: auto" %>
          <% end %>

          <div class="my-3 star-rating">
            <% if review.rating == 5 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i>
              </div>
            <% elsif review.rating == 4 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% elsif review.rating == 3 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% elsif review.rating == 2 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% elsif review.rating == 1 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% else %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% end %>
          </div>

          <p><%= review.content %></p>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Back to flat', flat_path(@flat), class: "btn btn-primary" %>
</div>

app/views/flats/search.html.erb
<% @search_colon = @query.present? ? ":" : ""  %>
<% @search_text =  @count > 1 || @count == 0 ? "stays" : "stay" %>
<h1 class="text-center">All Available Flats</h1>
<h3 class="text-center"><%= @query.capitalize %> <%= @search_colon %> <%= @count %> <%=@search_text %> found </h3>
<div class="px-5 flats-map-grid">
  <div id="map"
    style="width: 100%;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <div class="flat-cards">
    <% @flats.each do |flat| %>
    <div>
      <div class="card mb-2">
        <div class="card-block p-3">
          <div class="flats-photo">
            <% if flat.photo.key.present? %>
              <%= cl_image_tag flat.photo.key, class:"card-img-top search-image " %>
            <% else %>
            <%= image_tag("unknown.jpg", class:"card-img-top search-image") %>
            <% end %>
          </div>
          <strong><p class="card-title"><%= flat.address %></p></strong>
          <p class="card-subtitle text-muted"><span class="font-weight-bold">Price Per Day:</span> <%= flat.price_per_day %> Euros</p>
          <small class="card-text p-y-1"><span class="font-weight-bold">Capacity:</span> <%= flat.capacity %> people</small><br>
          <%= link_to 'Check it out!', flat, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<h1><%= link_to "Go back to home page", root_path, class: "btn btn-primary" %></h1>

app/views/flats/show.html.erb
<div class="container">
  <div class="flat_info">
    <h1>Beautiful place to rent in <%= @flat.city %></h1>
    <div class="d-flex justify-content-between">
      <% if @flat.photo.key.present? %>
        <%= cl_image_tag(@flat.photo.key, crop: :fill, class:"show-image") %>
      <% else %>
        <%= image_tag("unknown.jpg", class:"show-image") %>
      <% end %>
      <%= render "layouts/calendar", flat: @flat %>
    </div>

    <div class="book_button col-6">
      <%= simple_form_for [@flat, @booking] do |f| %>

        <input type="hidden" id="start_year" name="booking[first_day_of_booking(1i)]">
        <input type="hidden" id="start_month" name="booking[first_day_of_booking(2i)]">
        <input type="hidden" id="start_day" name="booking[first_day_of_booking(3i)]">

        <input type="hidden" id="end_year" name="booking[last_day_of_booking(1i)]">
        <input type="hidden" id="end_month" name="booking[last_day_of_booking(2i)]">
        <input type="hidden" id="end_day" name="booking[last_day_of_booking(3i)]">

        <%= f.submit :Book, class:"btn btn-primary" %>
      <% end %>
    </div>

    <div class="flat-data d-flex justify-content-between">
      <div class= "flat_show_info">
        <p><strong>Average Rating: </strong>
          <%= link_to reviews_flat_path do %>
            <%if @flat.average_rating[:average] == 5 %>
              <div class="d-flex">
                <p><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i>
                - (<%= @flat.average_rating[:num] %> reviews)</p>
              </div>
            <% elsif @flat.average_rating[:average] == 4 %>
              <div class="d-flex">
                <p><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i>
                - (<%= @flat.average_rating[:num] %> reviews)</p>
              </div>
            <% elsif @flat.average_rating[:average] == 3 %>
              <div class="d-flex">
                <p><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
                - (<%= @flat.average_rating[:num] %> reviews)</p>
              </div>
            <% elsif @flat.average_rating[:average] == 2 %>
              <div class="d-flex">
                <p><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
                - (<%= @flat.average_rating[:num] %> reviews)</p>
              </div>
            <% elsif @flat.average_rating[:average] == 1 %>
              <div class="d-flex">
                <p><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
                - (<%= @flat.average_rating[:num] %> reviews)</p>
              </div>
            <% else %>
              <div class="d-flex">
                <p><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
                - (<%= @flat.average_rating[:num] %> reviews)</p>
              </div>
            <% end %>
          <% end %>
        </p>
        <p><strong>Address: </strong><%= @flat.address %></p>
        <p><strong>Maximum capacity: </strong><%= @flat.capacity %></p>
        <p><strong>Description: </strong><%= @flat.description %></p>
        <p><strong>Price Per Day: </strong><%= @flat.price_per_day %> Euros</p>
        </div>
      </div>
      <hr>
      <div class="d-flex flex-row flat-options">


        <% if policy(Flat).create? %>
          <%= link_to "Create New Flat", new_flat_path, class: "btn btn-primary h-25" %>
        <% end %>
        <% if policy(@flat).edit? %>
          <%= link_to 'Edit', edit_flat_path(@flat), class:"btn btn-primary" %>
        <% end %>
        <% if policy(@flat).destroy? %>
          <%= link_to 'Delete', @flat, method: :delete, class:"btn btn-primary", data: {confirm: "sure?"} %>
        <% end %>
        <% if policy(Flat).create? %>
          <%= link_to "Back to All Flats", flats_path, class: "btn btn-primary"  %>
        <% end %>
      </div>
    </div>
  </div>
</div>