config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  get '/users/sign_out' => 'devise/sessions#destroy'

  get 'my_flats', to: 'flats#my_flats'

  resources :flats do
    resources :bookings, only: %i[new create]

    collection do
      get :search
    end

    member do
      get :reviews
    end

    resources :bookings, only: [ :new, :create ]
  end

  resources :bookings, except: [ :new, :index, :create ] do
    resources :reviews, only: [ :new, :create ]
  end

  resources :reviews, except: [ :new, :create ]

  get '/bookings', to: 'bookings#index'

  get '/error', to: 'errors#not_found'

  get "*path", to: redirect("/error")
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat

  has_one :review, dependent: :destroy

  validates :total_price, presence: true
  validates :first_day_of_booking, presence: true
  validates :last_day_of_booking, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_user
  before_action :find_booking, only: [ :show, :edit, :update, :destroy ]
  before_action :find_flat, only: [ :new, :create ]

  def index
    @bookings = policy_scope(Booking)
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def show
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = @user.id
    @booking.flat_id = @flat.id
    @booking.total_price = ((@booking.last_day_of_booking - @booking.first_day_of_booking).to_i) * @flat.price_per_day
    authorize @booking
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def edit
    authorize @booking
  end

  def update
    new_id = @booking.flat_id
    @flat = Flat.find(new_id)
    @booking.update(booking_params)
    @booking.total_price = ((@booking.last_day_of_booking - @booking.first_day_of_booking).to_i) * @flat.price_per_day
    authorize @booking
    if @booking.save
      redirect_to booking_path(@flat, @booking)
    else
      render :edit
    end
  end

  def destroy
    authorize @booking
    @booking.destroy
    redirect_to bookings_path
  end


  private

  def booking_params
    params.require(:booking).permit(:first_day_of_booking, :last_day_of_booking)
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def find_user
    @user = current_user
  end

  def find_flat
    @flat = Flat.find(params[:flat_id])
  end

  # def total_price
  #   @flat.price_per_day * @booking.date_booked.length
  # end
end

app/views/bookings/edit.html.erb
<h1>Edit your stay</h1>

<div class="container">
  <%= simple_form_for [ @booking ] do |f| %>
  <%= f.input :first_day_of_booking %>
  <%= f.input :last_day_of_booking %>
  <%= f.submit "Update", class: "btn btn-primary" %>
<% end %>
</div>

app/views/bookings/index.html.erb
<h1 class="text-center">Your Bookings</h1>
<div class="py-5">
  <div class="container">
    <div class="row hidden-md-up">
      <% @bookings.each do |booking| %>
        <% flat = Flat.find(booking.flat_id) %>
        <div class="col-md-4">
          <div class="card mb-2">
            <div class="card-block p-3">
              <% if flat.photo.key.present? %>
                <%= cl_image_tag booking.flat.photo.key, crop: :fill, class:"flat_pic card-img-top" %>
              <% else %>
                <%= image_tag("unknown.jpg", class:"flat_pic card-img-top") %>
              <% end %>
              <p class="card-title">City: <%= flat.city %></p>
              <p class="card-subtitle text-muted"><span class="font-weight-bold">Total Price:</span> <%= booking.total_price %> Euros</p>
              <small class="card-text p-y-1"><span class="font-weight-bold">Description:</span> <%= flat.description %> people</small><br>
              <%= link_to 'Check it out!', booking, class: "btn btn-primary" %> <br>
              <% if policy(booking).edit? %>
                <%= link_to 'Edit', edit_booking_path(booking), class: "btn btn-primary" %>
              <% end %>
              <% if policy(booking).destroy? %>
                <%= link_to 'Delete', booking, method: :delete, data: {confirm: "sure?"}, class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="container">
        <% if policy(Flat).create? %>
          <%= link_to "Back to All Flats!", flats_path, class:"btn btn-primary" %>
        <% end %>
        <%= link_to 'All your reviews', reviews_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<h1>New Booking</h1>
<div class="container">
  <%= simple_form_for [ @flat, @booking ] do |f| %>
    <%= f.input  :first_day_of_booking, label: 'Check-in' %>
    <%= f.input :last_day_of_booking, label: 'Check-out'  %>
    <div class="text-center">
      <%= f.submit "Book!", class: "btn btn-primary w-50" %><br>
      <%= link_to "Back to All Flats", flats_path, class: "btn btn-primary"  %>
      <%= link_to "Back to your Booking", bookings_path(@booking), class: "btn btn-primary"  %>
    </div>
  <% end %>
</div>

app/views/bookings/show.html.erb
<% flat = Flat.find(@booking.flat_id) %>
<div class="container">
  <div class="row d-flex align-items-center">
    <div class="col-8">
      <h3>Your Stay in <%= flat.country %> </h3>
    </div>
    <div class="col-4 d-flex justify-content-end">
      <%= link_to 'Back to your bookings', bookings_path, class: "btn btn-primary btn-sm" %>
    </div>
  </div>
  <div class="row booking_container">
    <div class="col-6">
      <% if flat.photo.key.present? %>
        <%= cl_image_tag flat.photo.key, crop: :fill, class:"flat_pic booking_flat_pic" %>
      <% else %>
        <%= image_tag("unknown.jpg", class:"flat_pic booking_flat_pic") %>
      <% end %>
    </div>
    <div class="info show_booking col-4">
      <p style="font-size: 16px;"><span class="font-weight-bold">From: </span><%= @booking.first_day_of_booking.strftime("%e-%m-%Y")  %></p>
      <p style="font-size: 16px;"><span class="font-weight-bold">To: </span><%= @booking.last_day_of_booking.strftime("%e-%m-%Y")  %></p>
      <p style="font-size: 16px;"><span class="font-weight-bold">Address: </span><%= flat.address  %></p>
      <p style="font-size: 16px;"><span class="font-weight-bold">Description: </span><%= flat.description  %></p>
      <p style="font-size: 16px;"><span class="font-weight-bold">Capacity: </span><%= flat.capacity  %></p>
      <p style="font-size: 16px;"><span class="font-weight-bold">City: </span><%= flat.city  %></p>
      <p style="font-size: 16px;"><span class="font-weight-bold">Country: </span><%= flat.country  %></p>
      <p style="font-size: 16px;"><span class="font-weight-bold">Total Price: </span><%= @booking.total_price  %> Euros.</p>
    </div>
    <div class="col-4 d-flex justify-content-start">
      <div>
        <% if @booking.review %>
        <h3>Your opinion</h3>
          <div class="card mb-2">
            <div class="card-block p-3">
              <h4 class="py-4"><%= flat.address %></h4>
              <div class="my-1">
                <% if @booking.review.rating == 5 %>
                  <div class="d-flex">
                    <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i>
                  </div>
                <% elsif @booking.review.rating == 4 %>
                  <div class="d-flex">
                    <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i>
                  </div>
                <% elsif @booking.review.rating == 3 %>
                  <div class="d-flex">
                    <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
                  </div>
                <% elsif @booking.review.rating == 2 %>
                  <div class="d-flex">
                    <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
                  </div>
                <% elsif @booking.review.rating == 1 %>
                  <div class="d-flex">
                    <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
                  </div>
                <% else %>
                  <div class="d-flex">
                    <i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
                  </div>
                <% end %>
              </div>
              <p><%= @booking.review.content %></p>
              <%= link_to "Your review", review_path(@booking.review), class: "btn btn-outline-dark" %>
            </div>
          </div>
        <% else %>
          <%= link_to 'Add a review', new_booking_review_path(@booking), class: "btn btn-primary mx-2" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="booking-options">
    <%= link_to "Delete this booking", booking_path(@booking), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary mx-2" %>
      <% if policy(@booking).edit? %>
      <%= link_to 'Edit this booking', edit_booking_path(@booking), class: "btn btn-primary mx-2" %>
    <% end %>
    <% if policy(@booking).destroy? %>
      <%= link_to 'Back to your bookings', bookings_path, class: "btn btn-primary mx-2" %>
    <% end %>
  </div>
</div>