config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  get '/users/sign_out' => 'devise/sessions#destroy'

  get 'my_flats', to: 'flats#my_flats'

  resources :flats do
    resources :bookings, only: %i[new create]

    collection do
      get :search
    end

    member do
      get :reviews
    end

    resources :bookings, only: [ :new, :create ]
  end

  resources :bookings, except: [ :new, :index, :create ] do
    resources :reviews, only: [ :new, :create ]
  end

  resources :reviews, except: [ :new, :create ]

  get '/bookings', to: 'bookings#index'

  get '/error', to: 'errors#not_found'

  get "*path", to: redirect("/error")
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_user
  before_action :find_booking, only: [ :new, :create ]
  before_action :find_review, only: [ :show, :edit, :update, :destroy ]

  def index
    reviews_all = policy_scope(Review)
    @reviews = reviews_all.select do |review|
      booking = Booking.find(review.booking_id)
      booking.user_id == @user.id
    end
  end

  def new
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.booking_id = @booking.id
    authorize @review
    @review.save
    if @review.save
      redirect_to review_path(@review)
    else
      render :new
    end
  end

  def show
    authorize @review
  end

  def edit
    authorize @review
  end

  def update
    authorize @review
    @review.update(review_params)

    redirect_to review_path(@review)
  end

  def destroy
    authorize @review
    @review.destroy
    redirect_to bookings_path
  end

  private

  def find_user
    @user = current_user
  end

  def find_booking
    @booking = Booking.find(params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end

  def find_review
    @review = Review.find(params[:id])
  end
end

app/views/reviews/edit.html.erb
<h1>Edit your review</h1>
<div class="container">
  <%= simple_form_for [ @review ] do |f| %>
    <%= f.input :rating, collection: [1, 2, 3, 4, 5] %>
    <%= f.input :content, hint: "Edit your coment for this review" %>
    <%= f.submit "Edit review", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/reviews/index.html.erb
<h1>My reviews</h1>
<div class="container">
  <div class="row d-flex justify-content-center">
    <% @reviews.each do |review| %>
      <% @booking = Booking.find(review.booking_id) %>
      <% @flat = Flat.find(@booking.flat_id) %>
      <div class="review-card col-4 shadow-sm m-2 border">
        <div>
          <% if @flat.photo.key.nil? %>
            <%= image_tag "no-image.png", class:"img-fluid width: 100% height: auto" %>
          <% else %>
            <%= cl_image_tag @flat.photo.key, class:"img-fluid width: 100% height: auto" %>
          <% end %>

          <div class="my-3 star-rating">
            <% if review.rating == 5 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i>
              </div>
            <% elsif review.rating == 4 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% elsif review.rating == 3 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% elsif review.rating == 2 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% elsif review.rating == 1 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% else %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% end %>
          </div>

          <p><%= review.content %></p>

          <p>From <strong><%= @booking.first_day_of_booking %></strong> to <strong><%= @booking.last_day_of_booking %></strong></p>
          <p>Total price <strong><%= @booking.total_price %>€</strong></p>

          <div>
            <%= link_to "View", review_path(review), class: "text-success" %>
            <%= link_to "Edit", edit_review_path(review), class: "text-warning" %>
            <%= link_to "Delete",
            review_path(review),
            method: :delete,
            data: { confirm: "Are you sure?" }, class: "text-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Bookings', bookings_path, class: "btn btn-primary" %>
</div>

app/views/reviews/new.html.erb
<% @flat = Flat.find(@booking.flat_id) %>
<h1>How was your stay at <strong class="text-muted"><%= @flat.address %></strong>?</h1>
<div class="container">
  <%= simple_form_for [ @booking, @review ] do |f| %>
    <%= f.input :rating, collection: [1, 2, 3, 4, 5] %>
    <%= f.input :content, hint: "Tell us more about your experience in #{@flat.address}" %>
    <%= f.submit "Add review", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/reviews/show.html.erb
<% @booking = Booking.find(@review.booking_id) %>
<% @flat = Flat.find(@booking.flat_id) %>
<div class="container">
  <div class="d-flex justify-content-around align-items-center">
    <h1>Your <strong class="text-muted"><%= @flat.address %></strong> review</h1>
    <%= link_to "Back to your stay", booking_path(@booking), class: "btn btn-primary btn-sm" %>
  </div>
  <div class="review-card d-flex row justify-content-around">
    <div class="col-5">
      <% if @flat.photo.key.nil? %>
        <%= image_tag "no-image.png", class:"review-image" %>
      <% else %>
        <%= cl_image_tag @flat.photo.key, class:"review-image" %>
      <% end %>
    </div>
    <div class="col-5">
      <div class="star-rating my-3">
        <p>Rating:</p>
        <% if @review.rating == 5 %>
          <div class="d-flex">
            <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i>
          </div>
        <% elsif @review.rating == 4 %>
          <div class="d-flex">
            <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i>
          </div>
        <% elsif @review.rating == 3 %>
          <div class="d-flex">
            <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
          </div>
        <% elsif @review.rating == 2 %>
          <div class="d-flex">
            <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
          </div>
        <% elsif @review.rating == 1 %>
          <div class="d-flex">
            <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
          </div>
        <% else %>
          <div class="d-flex">
            <i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
          </div>
        <% end %>
      </div>
      <p>Comment: <strong><%= @review.content %></strong></p>

      <p>From <strong><%= @booking.first_day_of_booking %></strong> to <strong><%= @booking.last_day_of_booking %></strong></p>
      <p>Total price <strong><%= @booking.total_price %>€</strong></p>

      <div>
        <%= link_to "Edit", edit_review_path(@review), class: "btn btn-primary btn-sm" %>
        <%= link_to "Delete",
        review_path(@review),
        method: :delete,
        data: { confirm: "Are you sure?" }, class: "btn btn-primary btn-sm" %>
      </div>
    </div>
  </div>
</div>