config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  get '/users/sign_out' => 'devise/sessions#destroy'

  get 'my_flats', to: 'flats#my_flats'

  resources :flats do
    resources :bookings, only: %i[new create]

    collection do
      get :search
    end

    member do
      get :reviews
    end

    resources :bookings, only: [ :new, :create ]
  end

  resources :bookings, except: [ :new, :index, :create ] do
    resources :reviews, only: [ :new, :create ]
  end

  resources :reviews, except: [ :new, :create ]

  get '/bookings', to: 'bookings#index'

  get '/error', to: 'errors#not_found'

  get "*path", to: redirect("/error")
end

app/views/layouts/_calendar.html.erb
<div class="calendar col-6" id="calendar-data" data-start-date="<%= flat.start_date.strftime("%m/%e/%Y") %>" data-end-date="<%= flat.end_date.strftime("%m/%e/%Y") %>" >
  <span>Select dates</span>
  <div id="reportrange" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%">
      <i class="fa fa-calendar"></i>&nbsp;
      <span></span> <i class="fa fa-caret-down"></i>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <hr id="footer_line">
  <ul id="footer_links">
   <li class="link_text">
      <%= link_to "Terms & conditions", "#"  %>
    </li>
    <li>
      <%= link_to "#" do %>
        <i class="fab fa-facebook-square"></i>
      <% end %>
    </li>
    <li>
      <%= link_to "#" do %>
        <i class="fab fa-instagram"></i>
      <% end %>
    </li>
    <li>
      <%= link_to "#" do %>
        <i class="fab fa-twitter-square"></i>
      <% end %>
    </li>
  </ul>
</footer>

app/views/layouts/_navbar.html.erb
 <nav class="navbar navbar-light justify-content-between">
 <!-- add propper link -->
  <div id="homepage_link">
    <%= link_to "airbnb ", root_path, id:"home_button_1" %><%= link_to " LeWagon", root_path, id:"home_button_2" %>
  </div>
  <div class="ms-auto">
    <form class="form-inline my-2 my-lg-0" action="/flats/search">
      <input class="form-control mr-sm-2" type="search" name="query" placeholder="Where are you going?" aria-label="Search" id="search-input">
      <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-expanded="false" id="login_menu">
        &#x1F464;
          </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="login_menu">
          <ul class="link_list">
            <% if user_signed_in? %>
              <% unless current_user.flats.any? %>
               <li><%= link_to "Become a host", new_flat_path %></li>
              <% else %>
                 <li><%= link_to "My flats", my_flats_path %></li>
                 <li><%= link_to "Add a new flat", new_flat_path %></li>
              <% end %>
              <li><%= link_to "My bookings", bookings_path %></li>
              <li><%= link_to "My reviews", reviews_path %></li>
              <li class="border-top my-2"><%= link_to "Log out", destroy_user_session_path %></li>
            <% else %>
              <li><%= link_to "Register", new_user_registration_path %></li>
              <li><%= link_to "Log in", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbLewagon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>

    <meta charset="utf-8">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>